name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$DROPLET_IP" << EOF
            set -e # Stop on errors

            export NVM_DIR="\$HOME/.nvm"
            [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh" # Load nvm
            [ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion" # Load nvm bash_completion
            nvm use 21.1.0
            cd /var/www/betta_inv_client_be/
            echo "Node.js version:"
            node -v || echo "Node.js not found"
            echo "NPM version:"
            npm -v || echo "NPM not found"
            echo "PATH:"
            echo $PATH
            git restore .
            git pull
            npm ci
            npm run build
            chmod -R 777 dist
            pm2 stop all || true
            npx prisma generate
            pm2 restart all
          EOF
